/** Create empty database, first script before any other object DDL **/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;
SET NUMERIC_ROUNDABORT OFF;
GO
:setvar DatabaseName "loconomics"
GO

CREATE DATABASE [$(DatabaseName)]
GO
ALTER DATABASE [$(DatabaseName)] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [$(DatabaseName)].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [$(DatabaseName)] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [$(DatabaseName)] SET ANSI_NULLS OFF
GO
ALTER DATABASE [$(DatabaseName)] SET ANSI_PADDING OFF
GO
ALTER DATABASE [$(DatabaseName)] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [$(DatabaseName)] SET ARITHABORT OFF
GO
ALTER DATABASE [$(DatabaseName)] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [$(DatabaseName)] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [$(DatabaseName)] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [$(DatabaseName)] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [$(DatabaseName)] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [$(DatabaseName)] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [$(DatabaseName)] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [$(DatabaseName)] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [$(DatabaseName)] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [$(DatabaseName)] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [$(DatabaseName)] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [$(DatabaseName)] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [$(DatabaseName)] SET READ_COMMITTED_SNAPSHOT ON
GO
ALTER DATABASE [$(DatabaseName)] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [$(DatabaseName)] SET  MULTI_USER
GO
ALTER DATABASE [$(DatabaseName)] SET DB_CHAINING OFF
GO
ALTER DATABASE [$(DatabaseName)] SET ENCRYPTION ON
GO
USE [$(DatabaseName)]
GO
