CREATE TABLE [dbo].[PricingVariableDefinition] (
    [PricingVariableID]          INT            NOT NULL,
    [PositionID]                 INT            NOT NULL,
    [PricingTypeID]              INT            NOT NULL,
    [InternalName]               VARCHAR (60)   NOT NULL,
    [IsProviderVariable]         BIT            CONSTRAINT [DF_PricingVariableDefinition_IsProviderVariable] DEFAULT ((0)) NOT NULL,
    [IsCustomerVariable]         BIT            CONSTRAINT [DF_PricingVariableDefinition_IsCustomerVariable] DEFAULT ((0)) NOT NULL,
    [DataType]                   VARCHAR (50)   NOT NULL,
    [VariableLabel]              NVARCHAR (100) NULL,
    [VariableLabelPopUp]         NVARCHAR (200) NULL,
    [VariableNameSingular]       NVARCHAR (60)  NULL,
    [VariableNamePlural]         NVARCHAR (60)  NULL,
    [NumberIncludedLabel]        NVARCHAR (100) NULL,
    [NumberIncludedLabelPopUp]   NVARCHAR (200) NULL,
    [HourlySurchargeLabel]       NVARCHAR (100) NULL,
    [MinNumberAllowedLabel]      NVARCHAR (100) NULL,
    [MinNumberAllowedLabelPopUp] NVARCHAR (200) NULL,
    [MaxNumberAllowedLabel]      NVARCHAR (100) NULL,
    [MaxNumberAllowedLabelPopUp] NVARCHAR (200) NULL,
    [CalculateWithVariableID]    INT            NULL,
    [Active]                     BIT            CONSTRAINT [DF_PricingVariableDefinition_Active] DEFAULT ((1)) NOT NULL,
    [language]      NVARCHAR (42) DEFAULT ('en-US') NOT NULL,
    [CreatedDate]                DATETIME       CONSTRAINT [DF_PricingVariableDefinition_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]                DATETIME       CONSTRAINT [DF_PricingVariableDefinition_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]                 VARCHAR (25)   CONSTRAINT [DF_PricingVariableDefinition_ModifiedBy] DEFAULT ('sys') NOT NULL,
    [MinMaxValuesList]           NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_PricingVariableDefinition] PRIMARY KEY CLUSTERED ([PricingVariableID] ASC, [PositionID] ASC, [PricingTypeID] ASC)
);

