CREATE TABLE [dbo].[xServiceProfessionalPricing] (
    [ServiceProfessionalPricingID] INT            IDENTITY (1, 1) NOT NULL,
    [PricingTypeID]                INT            NOT NULL,
    [ServiceProfessionalUserID]    INT            NOT NULL,
    [JobTitleID]                   INT            NOT NULL,
    [Name]                         VARCHAR (50)   NOT NULL,
    [Description]                  VARCHAR (1000) NULL,
    [Price]                        DECIMAL (7, 2) NULL,
    [Duration]                     INT            NOT NULL,
    [FirstTimeClientsOnly]         BIT            DEFAULT ((0)) NOT NULL,
    [NumberOfSessions]             INT            DEFAULT ((1)) NOT NULL,
    [language]      NVARCHAR (42) DEFAULT ('en-US') NOT NULL,
    [CreatedDate]                  DATETIME       NOT NULL,
    [UpdatedDate]                  DATETIME       NOT NULL,
    [ModifiedBy]                   VARCHAR (25)   NOT NULL,
    [Active]                       BIT            NOT NULL,
    [IsAddOn]                      BIT            DEFAULT ((0)) NOT NULL,
    [PriceRate]                    DECIMAL (7, 2) NULL,
    [PriceRateUnit]                NVARCHAR (30)  NULL,
    [IsPhone]                      BIT            DEFAULT ((0)) NOT NULL,
    [VisibleToClientID]            INT            DEFAULT ((0)) NOT NULL,
    [ParentBookingID]              INT            NULL,
    [MaxAvailableSpots]            INT            DEFAULT ((1)) NOT NULL,
    [MaxCapacity]                  INT            DEFAULT ((1)) NOT NULL,
    [MinSpots]                     INT            DEFAULT ((1)) NOT NULL,
    PRIMARY KEY CLUSTERED ([ServiceProfessionalPricingID] ASC)
);

